FGBook/config/routes.rb
FGBook::Application.routes.draw do
  resources :rooms
  resources :users

  root 'home#index'

end

FGBook/app/models/room.rb
class Room < ActiveRecord::Base
	def complete_name
		"#{title}, #{location}"
	end
end

FGBook/app/models/user.rb
class User < ActiveRecord::Base
	EMAIL_REGEXP = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
	
	validates_presence_of :email, :full_name, :location
	validates_format_of :email, with: EMAIL_REGEXP

	has_secure_password
end

FGBook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

FGBook/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@rooms = Room.take(3)
	end
end

FGBook/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:title, :locatino, :description)
    end
end

FGBook/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end
	
	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to @user, 
				notice: 'Cadastro criado com sucesso!'
		else
			render action: :new
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to @user, 
				notice: 'Cadastro atualizado com sucesso!'
		else
			render action: :edit
		end
	end

	private

	def user_params
		params.require(:user).permit(:email, :full_name, :location, :password, :password_confirmation)
	end
end

FGBook/app/helpers/application_helper.rb
module ApplicationHelper
end

FGBook/app/helpers/rooms_helper.rb
module RoomsHelper
end

FGBook/app/views/home/index.html.erb
<h1>Livros recém postados</h1>

<ul>
	<% @rooms.each do |room| %>
		<li>
			<%= link_to "#{room.title}, #{room.locatino}", room %>
		</li>
	<% end %>
</ul>

FGBook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FGBook</title>
	<link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<div id="header-wrap">
			<h1><%= link_to "FGBook", root_path %></h1>
			<nav>
				<ul>
					<li><%= link_to "Livros", rooms_path %></li>
					<li><%= link_to "Cadastro", new_user_path %></li>
				</ul>
			</nav>
		</div>
	</header>

	<div id="content">
		<% if notice.present? %>
			<p id="notice"><%= notice %></p>
		<% end %>
		<% if alert.present? %>
			<p id="alert"><%= alert %></p>
		<% end %>

<%= yield %>

</body>
</html>

FGBook/app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :locatino %><br>
    <%= f.text_field :locatino %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

FGBook/app/views/rooms/edit.html.erb
<h1>Editando livros</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @room %> |
<%= link_to 'Voltar', rooms_path %>

FGBook/app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de livros</h1>

<table>
  <thead>
    <tr>
      <th>Título</th>
      <th>Autor</th>
      <th>Descrição</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.title %></td>
        <td><%= room.locatino %></td>
        <td><%= room.description %></td>
        <td><%= link_to 'Mostrar', room %></td>
        <td><%= link_to 'Editar', edit_room_path(room) %></td>
        <td><%= link_to 'Destroir', room, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo livro', new_room_path %>

FGBook/app/views/rooms/new.html.erb
<h1>Novo livro</h1>

<%= render 'form' %>

<%= link_to 'Voltar', rooms_path %>

FGBook/app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Título:</strong>
  <%= @room.title %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @room.locatino %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @room.description %>
</p>

<%= link_to 'Editar', edit_room_path(@room) %> |
<%= link_to 'Voltar', rooms_path %>

FGBook/app/views/users/_form.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<h2>Infelizmente não foi possível completar a ação pois o formulário possui os seguintes erros:</h2>
		<ul>
			<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<%= form_for @user do |f| %>
	<p>
		<%= f.label :full_name %>
		<%= f.text_field :full_name %>
		<% if @user.errors.has_key? :full_name %>
			<div class="error_message">
				<%= @user.errors[:full_name].first %>
			</div>
		<% end %>
	</p>
	<p>
		<%= f.label :location %>
		<%= f.text_field :location %>
		<% if @user.errors.has_key? :location %>
			<div class="error_message">
				<%= @user.errors[:location].first %>
			</div>
		<% end %>
	</p>
	<p>
		<%= f.label :email %>
		<%= f.text_field :email %>
		<% if @user.errors.has_key? :email %>
			<div class="error_message">
				<%= @user.errors[:email].first %>
			</div>
		<% end %>
	</p>
	<p>
		<%= f.label :password %>
		<%= f.password_field :password %>
		<% if @user.errors.has_key? :password %>
			<div class="error_message">
				<%= @user.errors[:password].first %>
			</div>
		<% end %>
	</p>
	<p>
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
		<% if @user.errors.has_key? :password_confirmation %>
			<div class="error_message">
				<%= @user.errors[:password_confirmation].first %>
			</div>
		<% end %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

FGBook/app/views/users/edit.html.erb
<h1>Editar perfil</h1>

<%= render 'form' %>

<% link_to "Voltar ao perfil", @user %>

FGBook/app/views/users/new.html.erb
<h1>Cadastro</h1>

<%= render 'form' %>

<%= link_to "Voltar", root_path %>

FGBook/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Perfil: <%= @user.full_name %></h1>

<ul>
	<li>Localização: <%= @user.location %></li>
</ul>

<%= link_to 'Editar Perfil', edit_user_path(@user) %>

<%= link_to 'Home', root_path %>